### PR TITLE
added simple tests for bit_utils

### PR DESCRIPTION
**Pull request by erikfrojdh**
Added some simple tests for the bit_utils. (can be run using make test)

@thattil @Bechir-Brahem 
Open question can we find a better name for manipulate_bit?

### CODE REVIEW

**Comment by Bechir-Brahem** [comment]
works well for me. But shouldn't we add pytest to the requirements in setup.py?

For the name I couldn't find a better one for it

**Comment by erikfrojdh** [comment]
I'm torn on adding pytest to requirements... it's needed to run the tests but in principle not to use the gui.

**Comment by Bechir-Brahem** [comment]
I think that there is a solution for this but I couldn't make it work right now. 
https://stackoverflow.com/a/28842733

**Comment by thattil** [comment]
> Added some simple tests for the bit_utils. (can be run using make test)
> 
> @thattil @Bechir-Brahem Open question can we find a better name for manipulate_bit?
Sure, anytime. How about set_or_clear_bit? I also dont have much other ideas.. What about you?

**Review by thattil — APPROVED** [review]

**Pull request merged**
